export const TOKEN = {
	FETCH: "TOKEN_FETCH",
	FETCH_ERROR: "TOKEN_FETCH_ERROR",
	FETCH_SUCCESS: "TOKEN_FETCH_SUCCESS"
};

export const USER = {
	FETCH: "USER_FETCH",
	FETCH_ERROR: "USER_FETCH_ERROR",
	FETCH_SUCCESS: "USER_FETCH_SUCCESS",
	CHANGE_THEME: "USER_CHANGE_THEME"
};

export const NEW_RELEASES = {
	FETCH: "NEW_RELEASES_FETCH",
	FETCH_SUCCESS: "NEW_RELEASES_FETCH_SUCCESS",
	FETCH_ERROR: "NEW_RELEASES_FETCH_ERROR"
};

export const TOP_TRACKS = {
	FETCH: "TOP_TRACKS_FETCH",
	FETCH_SUCCESS: "TOP_TRACKS_FETCH_SUCCESS",
	FETCH_ERROR: "TOP_TRACKS_FETCH_ERROR"
};

export const RECENTLY_PLAYED = {
	FETCH: "RECENTLY_PLAYED_FETCH",
	FETCH_SUCCESS: "RECENTLY_PLAYED_FETCH_SUCCESS",
	FETCH_ERROR: "RECENTLY_PLAYED_FETCH_ERROR"
};

export const SONG = {
	// REQUEST_PLAY: "SONG_REQUEST_PLAY",
	// REQUEST_PAUSE: "SONG_REQUEST_PAUSE",
	// REQUEST_RESUME: "SONG_REQUEST_RESUME",
	// REQUEST_STOP: "SONG_REQUEST_STOP",
	// REQUEST_UPDATE_VOLUME: "SONG_REQUEST_UPDATE_VOLUME",
	// REQUEST_UPDATE_ELAPSED_TIME: "SONG_REQUEST_UPDATE_ELAPSED_TIME",

	PLAY: "SONG_PLAY",
	PAUSE: "SONG_PAUSE",
	RESUME: "SONG_RESUME",
	STOP: "SONG_STOP",
	UPDATE_VOLUME: "SONG_UPDATE_VOLUME",
	UPDATE_ELAPSED_TIME: "SONG_UPDATE_ELAPSED_TIME",
	// SEEK: "SONG_SEEK"
};
